-- ================================================================================================
-- 📂 项目：拾光谣 (Time Ballad) - Next.js + Supabase 全栈架构
-- 📝 版本：v5.0_Final 
-- 🤖 AI 阅读指南：
--    1. 本文件是数据库的【唯一真理源】。请勿擅自修改字段名。
--    2. 注释中的 [🔥 核心逻辑] 代表业务关键规则，必须严格遵守。
--    3. 注释中的 [💻 前端对接] 代表 UI 开发时的取数逻辑。
--    4. 所有的 RLS (Row Level Security) 策略已在此定义，前端无需在客户端层处理权限过滤。
-- ================================================================================================

-- [全局配置] 强制设置上海时区，防止日期偏差
alter database postgres set timezone to 'Asia/Shanghai';

-- 初始化 UUID 生成扩展
create extension if not exists "uuid-ossp";

-- ================================================================================================
-- 1. 用户系统 (Profiles)
-- ================================================================================================

-- 表：用户档案
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,        
  avatar text,
  role text default 'user' check (role in ('user', 'admin')), 
  
  -- 管理员收款码 (仅当 role='admin' 时有意义)
  payment_qr_code text, 
  
  created_at timestamptz default now(),
  last_active_at timestamptz 
);

alter table public.profiles enable row level security;
create policy "Public view profiles" on profiles for select using (true); -- 允许查看他人基础信息(如头像)
create policy "User update own" on profiles for update using (auth.uid() = id);

-- ================================================================================================
-- 2. 系统与枚举 (System & Config)
-- ================================================================================================

-- 表：待删除文件队列 (用于绕过 Edge Function 超时限制)
-- [🔥 核心逻辑] 业务表删除图片记录后，触发器会自动往这里写一条。
-- 你需要配置一个 Cron Job (定时任务) 每天调用 Edge Function 读取此表并执行 storage.remove()。
create table if not exists public.sys_storage_delete_queue (
  id bigint generated by default as identity primary key,
  bucket_name text not null, -- 'albums' | 'poses'
  file_path text not null,   
  created_at timestamptz default now()
);
alter table public.sys_storage_delete_queue enable row level security;
-- 仅管理员可读（用于清理脚本）
create policy "Admin only queue" on sys_storage_delete_queue for select using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- [新增] 表：约拍类型配置
-- [💻 前端对接] 预约页面的下拉菜单请从这里读取数据 (WHERE is_active = true)。
create table if not exists public.booking_types (
  id int generated by default as identity primary key,
  name text not null, -- 例如: '互勉', 'JK制服', '婚礼跟拍'
  is_active boolean default true, -- 管理员可软删除
  created_at timestamptz default now()
);
-- 预设数据
insert into public.booking_types (name) values ('互勉'), ('常规约拍'), ('婚礼跟拍'), ('活动记录');

alter table public.booking_types enable row level security;
create policy "Public read types" on booking_types for select using (true);
create policy "Admin manage types" on booking_types for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- ================================================================================================
-- 3. 统计系统 (Analytics)
-- ================================================================================================

-- 表：用户日活流水
create table if not exists public.user_active_logs (
  user_id uuid references auth.users(id) on delete cascade not null,
  active_date date default current_date, 
  created_at timestamptz default now(),
  primary key (user_id, active_date) -- 联合主键确保每日每人只有一条
);

-- 表：仪表盘每日快照 (缓存表，极大提升后台加载速度)
create table if not exists public.analytics_daily (
  date date primary key default current_date,
  new_users_count int default 0,    
  active_users_count int default 0 
);

alter table public.user_active_logs enable row level security;
alter table public.analytics_daily enable row level security;
create policy "Log write" on user_active_logs for insert with check (auth.uid() = user_id);
create policy "Admin read stats" on analytics_daily for select using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- ================================================================================================
-- 4. 摆姿资源 (Poses)
-- ================================================================================================

-- 表：拍照姿势
-- [💻 前端对接] 首页摇一摇数据源。
create table if not exists public.poses (
  id bigint generated by default as identity primary key,
  image_url text not null, -- Public Bucket URL
  storage_path text, 
  tags text[], 
  view_count int default 0, 
  created_at timestamptz default now()
);

create index if not exists poses_tags_idx on public.poses using gin (tags); -- 加速标签搜索

alter table public.poses enable row level security;
create policy "Public read poses" on poses for select using (true);
create policy "Admin manage poses" on poses for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- ================================================================================================
-- 5. 专属返图空间 (Albums)
-- ================================================================================================

-- 表：相册
-- [🔥 核心逻辑] RLS 默认为关闭 (False)。这意味着任何 SELECT * FROM albums 都会返回空。
-- 必须通过 RPC `get_album_content(key)` 携带密钥才能访问数据。
create table if not exists public.albums (
  id uuid default gen_random_uuid() primary key,
  access_key text not null unique, -- 访问密钥
  title text,
  cover_url text, 
  welcome_letter text, -- 管理员寄语
  enable_tipping boolean default true,
  created_at timestamptz default now()
);
alter table public.albums enable row level security;
create policy "Admin manage albums" on albums for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- 表：相册文件夹
create table if not exists public.album_folders (
  id uuid default gen_random_uuid() primary key,
  album_id uuid references public.albums(id) on delete cascade not null,
  name text not null,
  created_at timestamptz default now()
);
alter table public.album_folders enable row level security;
create policy "Admin manage folders" on album_folders for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- ================================================================================================
-- 6. 照片与互动 (Photos, Comments, Likes)
-- ================================================================================================

-- 表：照片
create table if not exists public.album_photos (
  id uuid default gen_random_uuid() primary key,
  album_id uuid references public.albums(id) on delete cascade not null,
  folder_id uuid references public.album_folders(id) on delete set null,
  
  url text not null,      -- Private Bucket Path (需要签名)
  width int, height int,  -- 用于瀑布流布局
  blurhash text,          -- 用于加载占位
  
  is_public boolean default false, -- [重要] True 则出现在照片墙
  
  view_count int default 0,
  like_count int default 0, 
  rating int default 0,     
  created_at timestamptz default now()
);

-- [索引优化] 加速照片墙查询
create index if not exists idx_photos_public_wall on public.album_photos(created_at desc) where is_public = true;

-- 表：照片评论
-- [🔥 核心安全] 评论功能仅限【专属空间】内部。照片墙(Public Wall)不显示也不允许评论。
create table if not exists public.photo_comments (
  id bigint generated by default as identity primary key,
  photo_id uuid references public.album_photos(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete set null,
  nickname text default '访客', -- 仅当 user_id 为空时使用
  content text not null,
  is_admin_reply boolean default false, 
  created_at timestamptz default now()
);

-- 表：点赞
-- [🔥 核心安全] 只有登录用户可以点赞。
create table if not exists public.photo_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null, -- Not Null 强制登录
  photo_id uuid references public.album_photos(id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(user_id, photo_id) -- 防止重复点赞
);

-- RLS 策略设置
alter table public.album_photos enable row level security;
alter table public.photo_comments enable row level security;
alter table public.photo_likes enable row level security;

-- 1. 照片权限：公开的可看，管理员全权
create policy "Public photos visible" on album_photos for select using (is_public = true);
create policy "Admin manage photos" on album_photos for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- 2. 评论权限：
-- [注意] 这里只开启 SELECT。INSERT 权限被完全关闭，必须通过 RPC 写入。
-- 这样确保了没有人能绕过后端逻辑（如检查密钥）直接写库。
create policy "View comments" on photo_comments for select using (true);
create policy "Admin manage comments" on photo_comments for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- 3. 点赞权限：仅登录用户可插入，且只能删自己的
create policy "User like" on photo_likes for insert with check (auth.uid() = user_id);
create policy "User unlike" on photo_likes for delete using (auth.uid() = user_id);
create policy "Public view likes" on photo_likes for select using (true);

-- ================================================================================================
-- 7. 预约系统 (Bookings)
-- ================================================================================================

-- 表：管理员锁档期 (休假设置)
create table if not exists public.booking_blackouts (
  id int generated by default as identity primary key,
  date date not null unique, 
  reason text,
  created_at timestamptz default now()
);
alter table public.booking_blackouts enable row level security;
create policy "Public read blackouts" on booking_blackouts for select using (true);
create policy "Admin manage blackouts" on booking_blackouts for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- 表：预约单
create table if not exists public.bookings (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) not null,
  
  -- 关联到配置表
  type_id int references public.booking_types(id), 
  
  booking_date date not null,
  time_slot_start time not null, 
  time_slot_end time not null,   
  location text not null,
  phone text not null,
  wechat text,
  contact_info jsonb,    
  notes text,
  
  status text default 'pending', -- pending | confirmed | finished | cancelled
  bound_album_id uuid references public.albums(id) on delete set null,
  admin_notes text,      
  created_at timestamptz default now()
);

-- [🔥 核心约束] 
-- 1. 每天只接一单 (状态非取消)
create unique index if not exists unique_active_daily_booking on bookings (booking_date) where status != 'cancelled';
-- 2. 每个用户同一时间只能有一个进行中的订单
create unique index if not exists one_active_booking_per_user on bookings (user_id) where status in ('pending', 'confirmed');

alter table public.bookings enable row level security;
create policy "User own bookings" on bookings for all using (auth.uid() = user_id);
create policy "Admin all bookings" on bookings for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- [Trigger] 约拍当天不可取消策略
create or replace function public.check_cancellation_policy()
returns trigger language plpgsql security definer as $$
declare
  is_admin boolean;
begin
  if new.status = 'cancelled' and old.status != 'cancelled' then
    -- 强制使用上海时间判断
    if (now() at time zone 'Asia/Shanghai')::date >= old.booking_date then
      select (role = 'admin') into is_admin from public.profiles where id = auth.uid();
      if is_admin is not true then
        raise exception '预约日期当天已无法自行取消，请联系摄影师。';
      end if;
    end if;
  end if;
  return new;
end;
$$;
create trigger trigger_check_cancellation before update on public.bookings for each row execute procedure public.check_cancellation_policy();

-- ================================================================================================
-- 8. 版本发布 (Releases)
-- ================================================================================================
create table if not exists public.app_releases (
  id bigint generated by default as identity primary key,
  version text not null,       
  platform text not null,      
  download_url text not null,
  update_log text,
  created_at timestamptz default now()
);
alter table public.app_releases enable row level security;
create policy "Public read releases" on app_releases for select using (true);
create policy "Admin manage releases" on app_releases for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- ================================================================================================
-- 9. 核心 RPC 接口 (前端调用层)
-- ================================================================================================

-- 1. 检查日期是否可预约
-- [💻 前端对接] 如果返回 false，日历上该日期置灰。
create or replace function public.check_date_availability(target_date date)
returns boolean language plpgsql security definer as $$
begin
  -- 检查是否被管理员锁住
  if exists (select 1 from public.booking_blackouts where date = target_date) then
    return false;
  end if;
  -- 检查是否已有订单
  if exists (select 1 from public.bookings where booking_date = target_date and status != 'cancelled') then
    return false;
  end if;
  return true;
end;
$$;

-- 2. 发表评论 (带密钥校验)
-- [🔥 安全核心] 无论是否登录，必须提供正确的 access_key 才能评论。
-- 这保证了只能在【专属空间】内评论，无法在【照片墙】评论（因为照片墙没有 Key）。
create or replace function public.post_album_comment(
  p_access_key text,
  p_photo_id uuid,
  p_content text
)
returns void language plpgsql security definer as $$
declare
  valid_album_id uuid;
  v_user_id uuid;
begin
  v_user_id := auth.uid(); -- 获取当前用户ID

  -- 越权检测：验证 Key 是否对应照片所属相册
  select a.id into valid_album_id
  from public.albums a
  join public.album_photos p on p.album_id = a.id
  where a.access_key = p_access_key and p.id = p_photo_id;

  if valid_album_id is null then
    raise exception '无权操作：密钥错误或照片不属于该空间';
  end if;

  insert into public.photo_comments (photo_id, user_id, content, nickname)
  values (p_photo_id, v_user_id, p_content, case when v_user_id is null then '访客' else null end);
end;
$$;

-- 3. 获取专属相册详情
-- [💻 前端对接] 返回相册信息 + 文件夹列表 + 照片列表
create or replace function public.get_album_content(input_key text)
returns jsonb language plpgsql security definer as $$
declare
  target_album_id uuid;
  result jsonb;
begin
  select id into target_album_id from public.albums where access_key = input_key;
  if target_album_id is null then return null; end if;

  select jsonb_build_object(
    'album', (
        select jsonb_build_object(
            'id', id, 'title', title, 'welcome_letter', welcome_letter, 'cover_url', cover_url, 'enable_tipping', enable_tipping,
            'admin_qr_path', (select payment_qr_code from profiles where role='admin' limit 1)
        ) from public.albums where id = target_album_id
    ),
    'folders', (
        select coalesce(json_agg(jsonb_build_object('id', id, 'name', name)), '[]'::json)
        from public.album_folders where album_id = target_album_id
    ),
    'photos', (
       select coalesce(json_agg(
           jsonb_build_object(
               'id', id, 'folder_id', folder_id, 'storage_path', url,
               'width', width, 'height', height, 'blurhash', blurhash,
               'is_public', is_public, 'rating', rating,
               -- 仅在专属空间内返回评论数据
               'comments', (
                   select coalesce(json_agg(
                       jsonb_build_object('nickname', nickname, 'content', content, 'is_admin', is_admin_reply, 'created_at', created_at)
                   ), '[]'::json) 
                   from public.photo_comments where photo_id = album_photos.id order by created_at asc
               )
           ) order by created_at desc
       ), '[]'::json)
       from public.album_photos where album_id = target_album_id
    )
  ) into result;
  
  return result;
end;
$$;

-- 4. 获取照片墙 (公开)
-- [🔥 核心逻辑] 这里故意【不返回】 comments 字段。
-- 即使数据库里有评论（来自专属空间），在照片墙上也拿不到数据，彻底防止显示。
create or replace function public.get_public_gallery(page_no int, page_size int)
returns jsonb language sql security definer as $$
  select json_agg(t) from (
    select 
      p.id, p.url as storage_path, p.width, p.height, p.blurhash, 
      p.like_count, p.view_count, p.created_at,
      -- 检查当前用户是否点过赞 (返回 boolean)
      exists(select 1 from public.photo_likes pl where pl.photo_id = p.id and pl.user_id = auth.uid()) as is_liked
    from public.album_photos p
    where p.is_public = true
    order by p.created_at desc
    limit page_size
    offset (page_no - 1) * page_size
  ) t;
$$;

-- ================================================================================================
-- 10. 自动化 Triggers
-- ================================================================================================

-- 新用户注册 -> 写入 Profiles
create or replace function public.handle_new_user() returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    'user'
  );
  -- 尝试更新日增用户统计
  insert into public.analytics_daily (date, new_users_count) values (current_date, 1)
  on conflict (date) do update set new_users_count = analytics_daily.new_users_count + 1;
  return new;
end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- 删除照片 -> 加入删除队列
create or replace function public.queue_storage_deletion() returns trigger language plpgsql security definer as $$
begin
  -- 根据表名判断存储桶和字段名
  if TG_TABLE_NAME = 'album_photos' and old.url is not null then
    insert into public.sys_storage_delete_queue (bucket_name, file_path)
    values ('albums', old.url);
  elsif old.storage_path is not null then
    insert into public.sys_storage_delete_queue (bucket_name, file_path)
    values ('poses', old.storage_path);
  end if;
  return old;
end; $$;
create trigger on_photo_deleted after delete on public.album_photos for each row execute procedure public.queue_storage_deletion();

-- 魔法过期逻辑 (可配合 pg_cron 或外部定时任务)
create or replace function public.cleanup_expired_data() returns void language plpgsql security definer as $$
begin
  -- 删除7天前且未公开的照片
  delete from public.album_photos where created_at < now() - interval '7 days' and is_public = false;
  -- 删除空文件夹
  delete from public.album_folders 
  where id not in (select distinct folder_id from public.album_photos where folder_id is not null)
  and created_at < now() - interval '24 hours';
end; $$;