-- ================================================================================================
-- 📂 项目：拾光谣 - 摆姿标签管理系统
-- 📝 版本：v2.0 - Pose Tags System (合并 002 + 004)
-- 🎯 目标：完整的摆姿标签管理系统，包含修复后的触发器
-- 📅 日期：2026-02-02
-- ================================================================================================

-- ================================================================================================
-- 1. 摆姿标签表
-- ================================================================================================

-- 表：摆姿标签
-- [💻 前端对接] 标签管理页面的数据源
create table if not exists public.pose_tags (
  id bigint generated by default as identity primary key,
  name text not null unique, -- 标签名称，唯一约束
  usage_count int default 0, -- 使用次数统计
  created_at timestamptz default now()
);

-- 索引优化
create index if not exists pose_tags_name_idx on public.pose_tags(name);

-- RLS 策略
alter table public.pose_tags enable row level security;
create policy "Public read tags" on pose_tags for select using (true);
create policy "Admin manage tags" on pose_tags for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- ================================================================================================
-- 2. 触发器：删除标签时自动从所有摆姿中移除该标签（修复版）
-- ================================================================================================

-- 删除旧触发器（如果存在）
drop trigger if exists trigger_remove_tag_from_poses on public.pose_tags;

-- 删除标签时自动从所有摆姿中移除该标签（改为AFTER DELETE）
create or replace function public.remove_tag_from_poses()
returns trigger language plpgsql security definer as $$
begin
  -- 从所有poses的tags数组中移除被删除的标签
  update public.poses
  set tags = array_remove(tags, old.name)
  where old.name = any(tags);

  return old;
end;
$$;

-- 改为AFTER DELETE，避免与usage_count更新冲突
create trigger trigger_remove_tag_from_poses
  after delete on public.pose_tags
  for each row
  execute procedure public.remove_tag_from_poses();

-- ================================================================================================
-- 3. 触发器：更新标签使用次数（修复版）
-- ================================================================================================

-- 删除旧触发器（如果存在）
drop trigger if exists trigger_update_tag_usage_count on public.poses;

-- 更新标签使用次数（添加存在性检查）
create or replace function public.update_tag_usage_count()
returns trigger language plpgsql security definer as $$
declare
  tag_name text;
begin
  -- 当poses表的tags字段变化时，更新相关标签的使用次数
  if TG_OP = 'INSERT' or TG_OP = 'UPDATE' then
    -- 更新新标签的使用次数
    foreach tag_name in array new.tags
    loop
      -- 只更新存在的标签
      update public.pose_tags
      set usage_count = (
        select count(*) from public.poses where tag_name = any(tags)
      )
      where name = tag_name;
    end loop;
  end if;

  if TG_OP = 'DELETE' or TG_OP = 'UPDATE' then
    -- 更新旧标签的使用次数
    foreach tag_name in array old.tags
    loop
      -- 只更新存在的标签（如果标签已被删除则跳过）
      update public.pose_tags
      set usage_count = (
        select count(*) from public.poses where tag_name = any(tags)
      )
      where name = tag_name;
    end loop;
  end if;

  return new;
end;
$$;

create trigger trigger_update_tag_usage_count
  after insert or update or delete on public.poses
  for each row
  execute procedure public.update_tag_usage_count();

-- ================================================================================================
-- 完成
-- ================================================================================================

DO $$
BEGIN
  RAISE NOTICE '✅ 摆姿标签系统创建完成！';
  RAISE NOTICE '📊 已创建表：pose_tags';
  RAISE NOTICE '🔄 已创建触发器：删除标签自动清理 + 使用次数统计';
  RAISE NOTICE '🐛 已修复：触发器冲突问题（AFTER DELETE）';
END $$;
