-- ================================================================================================
-- 📂 项目：拾光谣 (Time Ballad) - 核心数据库结构
-- 📝 版本：v2.0_Consolidated
-- 🎯 目标：核心表结构、用户系统、摆姿系统、相册系统、照片系统、版本发布
-- 📅 日期：2026-02-05
-- 🔄 合并自：001, 002, 007, 010, 09_fix_user_registration.sql, 14_unify_timezone_handling.sql
-- ================================================================================================

-- [全局配置] 设置UTC时区，与应用层保持一致
ALTER DATABASE postgres SET timezone TO 'UTC';

-- 初始化 UUID 生成扩展
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ================================================================================================
-- 1. 用户系统 (Profiles)
-- ================================================================================================

-- 表：用户档案
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  name text,
  nickname text,
  avatar text,
  role text DEFAULT 'user' CHECK (role IN ('user', 'admin')),

  -- 联系方式
  phone text,
  wechat text,

  -- 管理员收款码 (仅当 role='admin' 时有意义)
  payment_qr_code text,

  created_at timestamptz DEFAULT now(),
  last_active_at timestamptz
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_profiles_phone ON public.profiles(phone) WHERE phone IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_profiles_wechat ON public.profiles(wechat) WHERE wechat IS NOT NULL;

-- RLS 策略
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public view profiles" ON profiles FOR SELECT USING (true);
CREATE POLICY "User update own" ON profiles FOR UPDATE USING (auth.uid() = id);

-- 字段注释
COMMENT ON COLUMN public.profiles.nickname IS '用户昵称，用于评论显示';
COMMENT ON COLUMN public.profiles.phone IS '用户手机号';
COMMENT ON COLUMN public.profiles.wechat IS '用户微信号';

-- ================================================================================================
-- 2. 统计系统 (Analytics)
-- ================================================================================================

-- 表：用户日活流水
CREATE TABLE IF NOT EXISTS public.user_active_logs (
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  active_date date DEFAULT CURRENT_DATE,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (user_id, active_date)
);

-- 表：仪表盘每日快照 (缓存表，极大提升后台加载速度)
CREATE TABLE IF NOT EXISTS public.analytics_daily (
  date date PRIMARY KEY DEFAULT CURRENT_DATE,
  new_users_count int DEFAULT 0,
  active_users_count int DEFAULT 0
);

-- RLS 策略
ALTER TABLE public.user_active_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_daily ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Log write" ON user_active_logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admin read stats" ON analytics_daily FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- ================================================================================================
-- 3. 摆姿资源系统 (Poses & Tags)
-- ================================================================================================

-- 表：拍照姿势
CREATE TABLE IF NOT EXISTS public.poses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url text NOT NULL,
  storage_path text,
  tags text[],
  view_count int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS poses_tags_idx ON public.poses USING gin (tags);

-- 表：摆姿标签
CREATE TABLE IF NOT EXISTS public.pose_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  usage_count int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pose_tags_name_idx ON public.pose_tags(name);

-- RLS 策略
ALTER TABLE public.poses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read poses" ON poses FOR SELECT USING (true);
CREATE POLICY "Admin manage poses" ON poses FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

ALTER TABLE public.pose_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read tags" ON pose_tags FOR SELECT USING (true);
CREATE POLICY "Admin manage tags" ON pose_tags FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- ================================================================================================
-- 4. 专属返图空间 (Albums)
-- ================================================================================================

-- 表：相册
CREATE TABLE IF NOT EXISTS public.albums (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  access_key text NOT NULL UNIQUE,
  title text,
  cover_url text,
  welcome_letter text,
  recipient_name text DEFAULT '拾光者',
  enable_tipping boolean DEFAULT true,
  donation_qr_code_url text,
  expires_at timestamptz,
  created_by uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_albums_expires_at ON public.albums(expires_at) WHERE expires_at IS NOT NULL;

-- 表：相册文件夹
CREATE TABLE IF NOT EXISTS public.album_folders (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  album_id uuid REFERENCES public.albums(id) ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- RLS 策略
ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admin manage albums" ON albums FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

ALTER TABLE public.album_folders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admin manage folders" ON album_folders FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 字段注释
COMMENT ON COLUMN public.albums.expires_at IS '相册过期时间';
COMMENT ON COLUMN public.albums.recipient_name IS '收件人名称，默认为"拾光者"';
COMMENT ON COLUMN public.albums.donation_qr_code_url IS '赞赏码图片URL';
COMMENT ON COLUMN public.albums.created_by IS '相册创建者，用于级联删除';

-- ================================================================================================
-- 5. 照片与互动 (Photos, Comments, Likes)
-- ================================================================================================

-- 表：照片
CREATE TABLE IF NOT EXISTS public.album_photos (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  album_id uuid REFERENCES public.albums(id) ON DELETE CASCADE NOT NULL,
  folder_id uuid REFERENCES public.album_folders(id) ON DELETE SET NULL,

  -- 兼容字段（保留用于向后兼容）
  url text,

  -- 多版本图片URL
  thumbnail_url text,
  preview_url text,
  original_url text,

  width int,
  height int,
  blurhash text,

  is_public boolean DEFAULT false,

  view_count int DEFAULT 0,
  like_count int DEFAULT 0,
  rating int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_photos_public_wall ON public.album_photos(created_at DESC) WHERE is_public = true;
CREATE INDEX IF NOT EXISTS idx_album_photos_created_at ON public.album_photos(created_at) WHERE is_public = false;
CREATE INDEX IF NOT EXISTS idx_album_photos_thumbnail_url ON public.album_photos(thumbnail_url) WHERE thumbnail_url IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_album_photos_preview_url ON public.album_photos(preview_url) WHERE preview_url IS NOT NULL;

-- 表：照片评论
CREATE TABLE IF NOT EXISTS public.photo_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  photo_id uuid REFERENCES public.album_photos(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  nickname text DEFAULT '访客',
  content text NOT NULL,
  is_admin_reply boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- 表：点赞
CREATE TABLE IF NOT EXISTS public.photo_likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  photo_id uuid REFERENCES public.album_photos(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, photo_id)
);

-- RLS 策略
ALTER TABLE public.album_photos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public photos visible" ON album_photos FOR SELECT USING (is_public = true);
CREATE POLICY "Admin manage photos" ON album_photos FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

ALTER TABLE public.photo_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "View comments" ON photo_comments FOR SELECT USING (true);
CREATE POLICY "Admin manage comments" ON photo_comments FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

ALTER TABLE public.photo_likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "User like" ON photo_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "User unlike" ON photo_likes FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Public view likes" ON photo_likes FOR SELECT USING (true);

-- 字段注释
COMMENT ON COLUMN public.album_photos.url IS '兼容字段 - 新数据使用 thumbnail_url/preview_url/original_url';
COMMENT ON COLUMN public.album_photos.thumbnail_url IS '速览图URL - 用于列表快速加载 (300px, 质量75)';
COMMENT ON COLUMN public.album_photos.preview_url IS '高质量预览URL - 用于点击预览 (1200px, 质量85)';
COMMENT ON COLUMN public.album_photos.original_url IS '原图URL - 仅返图空间，用于下载 (完整质量)';

-- ================================================================================================
-- 6. 版本发布 (Releases)
-- ================================================================================================

CREATE TABLE IF NOT EXISTS public.app_releases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version text NOT NULL,
  platform text NOT NULL,
  download_url text NOT NULL,
  update_log text,
  force_update boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.app_releases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read releases" ON app_releases FOR SELECT USING (true);
CREATE POLICY "Admin manage releases" ON app_releases FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

COMMENT ON COLUMN public.app_releases.force_update IS '是否强制更新：true=强制更新（弹窗不可关闭），false=可选更新（弹窗可关闭）';

-- ================================================================================================
-- 7. 核心 RPC 接口
-- ================================================================================================

-- 发表评论 (带密钥校验)
CREATE OR REPLACE FUNCTION public.post_album_comment(
  p_access_key text,
  p_photo_id uuid,
  p_content text
)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  valid_album_id uuid;
  v_user_id uuid;
  v_nickname text;
BEGIN
  v_user_id := auth.uid();

  -- 越权检测：验证 Key 是否对应照片所属相册
  SELECT a.id INTO valid_album_id
  FROM public.albums a
  JOIN public.album_photos p ON p.album_id = a.id
  WHERE a.access_key = p_access_key AND p.id = p_photo_id;

  IF valid_album_id IS NULL THEN
    RAISE EXCEPTION '无权操作：密钥错误或照片不属于该空间';
  END IF;

  -- 获取用户昵称（如果已登录）
  IF v_user_id IS NOT NULL THEN
    SELECT nickname INTO v_nickname FROM public.profiles WHERE id = v_user_id;
  END IF;

  INSERT INTO public.photo_comments (photo_id, user_id, content, nickname)
  VALUES (p_photo_id, v_user_id, p_content, COALESCE(v_nickname, '访客'));
END;
$$;

-- 获取照片墙 (公开)
CREATE OR REPLACE FUNCTION public.get_public_gallery(page_no int, page_size int)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER AS $$
  SELECT json_agg(t) FROM (
    SELECT
      p.id,
      COALESCE(p.thumbnail_url, p.url) as thumbnail_url,
      COALESCE(p.preview_url, p.url) as preview_url,
      p.width, p.height, p.blurhash,
      p.like_count, p.view_count, p.created_at,
      EXISTS(SELECT 1 FROM public.photo_likes pl WHERE pl.photo_id = p.id AND pl.user_id = auth.uid()) as is_liked
    FROM public.album_photos p
    WHERE p.is_public = true
    ORDER BY p.created_at DESC
    LIMIT page_size
    OFFSET (page_no - 1) * page_size
  ) t;
$$;

-- ================================================================================================
-- 8. 自动化 Triggers
-- ================================================================================================

-- 新用户注册 -> 写入 Profiles (修复版：从 user_metadata 读取手机号，设置默认用户名)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, nickname, phone, role)
  VALUES (
    new.id,
    new.email,
    '拾光者', -- 默认用户名
    '拾光者', -- 默认昵称
    new.raw_user_meta_data->>'phone', -- 从 user_metadata 中读取手机号
    'user'
  );

  -- 更新日增用户统计
  INSERT INTO public.analytics_daily (date, new_users_count) VALUES (CURRENT_DATE, 1)
  ON CONFLICT (date) DO UPDATE SET new_users_count = analytics_daily.new_users_count + 1;

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_new_user();

-- 更新用户最后活跃时间
CREATE OR REPLACE FUNCTION public.update_last_active()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.profiles
  SET last_active_at = now()
  WHERE id = new.user_id;
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_user_active ON public.user_active_logs;
CREATE TRIGGER on_user_active
  AFTER INSERT ON public.user_active_logs
  FOR EACH ROW
  EXECUTE FUNCTION public.update_last_active();

-- 删除标签时自动从所有摆姿中移除该标签
CREATE OR REPLACE FUNCTION public.remove_tag_from_poses()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.poses
  SET tags = array_remove(tags, old.name)
  WHERE old.name = ANY(tags);
  RETURN old;
END;
$$;

DROP TRIGGER IF EXISTS trigger_remove_tag_from_poses ON public.pose_tags;
CREATE TRIGGER trigger_remove_tag_from_poses
  AFTER DELETE ON public.pose_tags
  FOR EACH ROW
  EXECUTE PROCEDURE public.remove_tag_from_poses();

-- 更新标签使用次数
CREATE OR REPLACE FUNCTION public.update_tag_usage_count()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  tag_name text;
BEGIN
  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    FOREACH tag_name IN ARRAY new.tags
    LOOP
      UPDATE public.pose_tags
      SET usage_count = (
        SELECT count(*) FROM public.poses WHERE tag_name = ANY(tags)
      )
      WHERE name = tag_name;
    END LOOP;
  END IF;

  IF TG_OP = 'DELETE' OR TG_OP = 'UPDATE' THEN
    FOREACH tag_name IN ARRAY old.tags
    LOOP
      UPDATE public.pose_tags
      SET usage_count = (
        SELECT count(*) FROM public.poses WHERE tag_name = ANY(tags)
      )
      WHERE name = tag_name;
    END LOOP;
  END IF;

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trigger_update_tag_usage_count ON public.poses;
CREATE TRIGGER trigger_update_tag_usage_count
  AFTER INSERT OR UPDATE OR DELETE ON public.poses
  FOR EACH ROW
  EXECUTE PROCEDURE public.update_tag_usage_count();

-- ================================================================================================
-- 完成
-- ================================================================================================

DO $$
BEGIN
  RAISE NOTICE '✅ 核心数据库结构创建完成！';
  RAISE NOTICE '📊 已创建：用户系统、统计系统、摆姿系统、相册系统、照片系统、版本发布';
  RAISE NOTICE '🔒 RLS 策略已配置';
  RAISE NOTICE '⚡ 触发器已设置';
  RAISE NOTICE '🔄 已整合：用户注册修复、UTC时区设置';
END $$;
