export const WALL_THUMBNAIL_MAX_WIDTH = 1280;
export const WALL_PREVIEW_MAX_WIDTH = 2560;

export const WALL_THUMBNAIL_MAX_SIZE_MB = 0.9;
export const WALL_PREVIEW_MAX_SIZE_MB = 3.5;

export const WALL_THUMBNAIL_INITIAL_QUALITY = 0.82;
export const WALL_PREVIEW_INITIAL_QUALITY = 0.92;

export const WALL_THUMBNAIL_QUALITY = 82;
export const WALL_PREVIEW_QUALITY = 92;
